#!/bin/sh
#
#  xfce4
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#

PATH=/bin:/usr/bin:/usr/local/bin
export PATH

# Lock by light-locker or dm-tool, if a respective daemon is running
for lock_cmd in \
    "light-locker-command -l" \
    "dm-tool lock"
do
    $lock_cmd >/dev/null 2>&1 && exit
done

# else access locking failed
exit 1

